<?php

namespace SiteBundle\Entity\Repository;

/**
 * ParametroEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametroEmailRepository extends \Doctrine\ORM\EntityRepository
{
}
