<?php

namespace SiteBundle\Entity\Repository;

/**
 * PostagemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostagemRepository extends \Doctrine\ORM\EntityRepository
{
}
